#!/usr/bin/env bash
set -euo pipefail

# Compares the ABI surface of the working tree against the same contracts at a
# base revision. Entries are keyed by function selector and event topic0, so
# reordering or reformatting by the toolchain never produces a diff.
#
# Nothing is committed. The published ABI is a release artifact, generated by
# shell/create_artifacts.sh into a gitignored artifacts/ and published on tag,
# so the baseline is the base branch rather than a snapshot in the repository.
#
# Usage: check_abi.sh [base-ref]      (or ABI_BASE_REF=<ref>)
#
# Exit codes:
#   0  ABI unchanged
#   1  ABI changed, but only additively
#   2  ABI compatibility break
#   3  the check could not run

# The scope is read out of shell/create_artifacts.sh rather than repeated here,
# because a second hand-maintained list drifts the moment a contract is added to
# the published package and not to this check. Added to it is
# AdminVerifierWhitelist, which is published nowhere but whose signatures the
# dapp seed script calls by literal string through `cast send`, so they cannot
# break at compile time either.
PUBLISHER="$(dirname "${BASH_SOURCE[0]}")/create_artifacts.sh"
UNPUBLISHED_CONTRACTS=(AdminVerifierWhitelist)

if [ ! -f "$PUBLISHER" ]; then
    echo "ERROR: $PUBLISHER not found, so the published ABI scope cannot be read." >&2
    exit 3
fi

mapfile -t PUBLISHED_CONTRACTS < <(
    sed -n 's|^extract_abi "\$ROOT_DIR/out/[^/]*\.sol/\([A-Za-z0-9_]*\)\.json".*|\1|p' "$PUBLISHER"
)

# A pattern that stops matching would leave the scope empty, and the check would
# then report a pass having compared nothing.
if [ ${#PUBLISHED_CONTRACTS[@]} -eq 0 ]; then
    echo "ERROR: no extract_abi calls could be read from $PUBLISHER, so this check" >&2
    echo "would compare nothing. Has the publisher's call format changed?" >&2
    exit 3
fi

mapfile -t CONTRACTS < <(
    printf '%s\n' "${PUBLISHED_CONTRACTS[@]}" "${UNPUBLISHED_CONTRACTS[@]}" | sort -u
)

BASE_REF="${1:-${ABI_BASE_REF:-origin/main}}"
REPO_ROOT=$(git rev-parse --show-toplevel)
BASE_TREE=""
BASE_TREE_PARENT=""

# Invoked through the EXIT trap below, so the base worktree is removed even
# when the check exits early.
# shellcheck disable=SC2329
cleanup() {
    if [ -n "$BASE_TREE" ] && [ -d "$BASE_TREE" ]; then
        git worktree remove --force "$BASE_TREE" >/dev/null 2>&1 || true
    fi
    if [ -n "$BASE_TREE_PARENT" ]; then
        rm -rf -- "${BASE_TREE_PARENT:?}"
        git worktree prune
    fi
}
trap cleanup EXIT

if ! BASE_SHA=$(git rev-parse --verify --quiet "${BASE_REF}^{commit}"); then
    echo "ERROR: base revision '$BASE_REF' does not resolve, so there is nothing" >&2
    echo "to compare against. Pass one explicitly: check_abi.sh <base-ref>" >&2
    exit 3
fi

# Comparing a revision against an identical tree would report a pass having
# verified nothing, which is worse than not running at all. Uncommitted work
# against HEAD is a real comparison, so only a clean tree is refused - which is
# exactly the CI case, where the checkout is always clean.
if [ "$BASE_SHA" = "$(git rev-parse 'HEAD^{commit}')" ] && [ -z "$(git status --porcelain -- src/)" ]; then
    echo "ERROR: base revision '$BASE_REF' is HEAD and src/ is unmodified, so the" >&2
    echo "comparison would verify nothing. Refusing to report a pass." >&2
    exit 3
fi

# Builds explicitly rather than letting `forge inspect` do it, because inspect
# adds its own field to the output selection and invalidates the build cache,
# forcing the next `forge build` to recompile every file.
build_tree() {
    local root=$1 label=$2
    if ! forge build --root "$root" >/dev/null; then
        echo "ERROR: forge build failed for the $label tree." >&2
        exit 3
    fi
}

# `git worktree add` leaves submodules empty. When the base pins the same
# revisions as the working tree - the normal case - the existing lib/ is reused,
# which is both correct and instant. A change that bumps a dependency gets a
# real checkout instead, so the base is never built against the wrong library.
prepare_base_libs() {
    local tree=$1 base_pins current_pins
    base_pins=$(git ls-tree "$BASE_SHA" lib/ | awk '$2 == "commit" { print $3, $4 }' | sort)
    current_pins=$(git submodule status | awk '{ sub(/^[-+U]/, "", $1); print $1, $2 }' | sort)

    if [ "$base_pins" = "$current_pins" ]; then
        rm -rf -- "${tree:?}/lib"
        ln -s "$REPO_ROOT/lib" "$tree/lib"
    elif ! git -C "$tree" submodule update --init >/dev/null 2>&1; then
        echo "ERROR: could not check out the submodules of $BASE_REF." >&2
        exit 3
    fi
}

# Emits the selector/topic0 fingerprint of one contract's ABI.
# Signatures are canonical: contract and enum parameters collapse to their
# underlying ABI type, so renaming an interface does not shift a hash.
abi_fingerprint() {
    local root=$1 contract=$2
    local artifact abi rows kind signature indexed anonymous mutability outputs hash
    artifact="$root/out/$contract.sol/$contract.json"

    # set -e does not abort a function running inside a command substitution, so
    # every failure below is checked explicitly. Without this a missing artifact
    # yields an empty ABI, which would be misreported as "everything removed".
    if [ ! -f "$artifact" ]; then
        echo "ERROR: no build artifact at $artifact." >&2
        return 1
    fi

    if ! abi=$(jq -c '.abi' "$artifact"); then
        echo "ERROR: could not read the ABI from $artifact." >&2
        return 1
    fi

    if [ "$(echo "$abi" | jq -r 'type' 2>/dev/null || true)" != "array" ]; then
        echo "ERROR: $artifact does not contain an ABI array." >&2
        return 1
    fi

    # Fields are joined with US (0x1f) rather than tabs: tab is IFS whitespace,
    # so `read` would coalesce runs of them and silently drop empty fields,
    # shifting every later field left for zero-argument entries.
    if ! rows=$(echo "$abi" | jq -r '
        def canon:
            if (.type | startswith("tuple")) then
                "(" + ((.components // []) | map(canon) | join(",")) + ")" + (.type | ltrimstr("tuple"))
            else
                .type
            end;
        .[]
        | select(.type == "function" or .type == "event" or .type == "error")
        | [
            .type,
            (.name + "(" + ((.inputs // []) | map(canon) | join(",")) + ")"),
            ((.inputs // []) | map(if .indexed then "1" else "0" end) | join("")),
            (if .anonymous then "true" else "false" end),
            (.stateMutability // ""),
            ((.outputs // []) | map(canon) | join(","))
        ]
        | join("")
    '); then
        echo "ERROR: could not read the ABI entries of $contract." >&2
        return 1
    fi

    while IFS=$'\x1f' read -r kind signature indexed anonymous mutability outputs; do
        [ -n "$kind" ] || continue
        if ! hash=$(cast keccak "$signature"); then
            echo "ERROR: 'cast keccak' failed for '$signature'." >&2
            exit 1
        fi
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$kind" "$hash" "$signature" "$indexed" "$anonymous" "$mutability" "$outputs"
    done <<<"$rows" | jq -S -R -s --arg contract "$contract" '
        [splits("\n") | select(length > 0) | [splits("\t")]] as $rows
        | {
            contract: $contract,
            functions: (
                $rows | map(select(.[0] == "function"))
                | map({key: .[1][0:10], value: {signature: .[2], stateMutability: .[5], outputs: .[6]}})
                | from_entries
            ),
            events: (
                $rows | map(select(.[0] == "event"))
                | map({key: .[1], value: {signature: .[2], indexed: .[3], anonymous: (.[4] == "true")}})
                | from_entries
            ),
            errors: (
                $rows | map(select(.[0] == "error"))
                | map({key: .[1][0:10], value: {signature: .[2]}})
                | from_entries
            )
        }
    '
}

removed_keys() {
    jq -r -n --argjson a "$1" --argjson b "$2" --arg s "$3" \
        '($a[$s] | keys) - ($b[$s] | keys) | .[]'
}

common_keys() {
    jq -r -n --argjson a "$1" --argjson b "$2" --arg s "$3" \
        '$a[$s] | keys[] | select(. as $k | $b[$s] | has($k))'
}

# A process substitution discards its exit status, so each key query below is
# captured and checked instead. A malformed fingerprint would otherwise read as
# an empty key set, and the check would conclude that nothing changed.
compare_error() {
    echo "ERROR: could not compare '$1' against $BASE_REF." >&2
    exit 3
}

# Reports whether state mutability moved in a direction that breaks callers.
# Losing staticcall-ability breaks eth_call consumers; losing payable breaks
# callers that send value. The reverse of either is safe.
mutability_change() {
    local before=$1 after=$2
    local static_before=false static_after=false
    local payable_before=false payable_after=false

    if [ "$before" = "view" ] || [ "$before" = "pure" ]; then static_before=true; fi
    if [ "$after" = "view" ] || [ "$after" = "pure" ]; then static_after=true; fi
    if [ "$before" = "payable" ]; then payable_before=true; fi
    if [ "$after" = "payable" ]; then payable_after=true; fi

    if { $static_before && ! $static_after; } || { $payable_before && ! $payable_after; }; then
        echo "tightened"
    elif { ! $static_before && $static_after; } || { ! $payable_before && $payable_after; }; then
        echo "relaxed"
    else
        echo "same"
    fi
}

echo "Comparing against $BASE_REF ($BASE_SHA)."

BASE_TREE_PARENT=$(mktemp -d)
BASE_TREE="$BASE_TREE_PARENT/base"
if ! git worktree add --detach "$BASE_TREE" "$BASE_SHA" >/dev/null 2>&1; then
    echo "ERROR: could not check out $BASE_REF for comparison." >&2
    exit 3
fi
prepare_base_libs "$BASE_TREE"
build_tree "$BASE_TREE" "base"
build_tree "$REPO_ROOT" "working"

# A function or event is reachable only through its selector/topic0, so a
# caller breaks the moment a key disappears. Renames, retypes and most reorders
# surface here as a removal, because each of them changes the hash. Swapping two
# parameters of the same type does not: the canonical signature is unchanged, so
# no selector-based check can see it.
breaking=false
additive=false

for contract in "${CONTRACTS[@]}"; do
    if ! current=$(abi_fingerprint "$REPO_ROOT" "$contract"); then
        exit 3
    fi

    if [ ! -f "$BASE_TREE/out/$contract.sol/$contract.json" ]; then
        echo "NOTE: '$contract' does not exist at $BASE_REF - it is newly in scope."
        additive=true
        continue
    fi

    if ! previous=$(abi_fingerprint "$BASE_TREE" "$contract"); then
        exit 3
    fi

    if [ "$current" = "$previous" ]; then
        continue
    fi

    for section in functions events errors; do
        if ! gone=$(removed_keys "$previous" "$current" "$section"); then
            compare_error "$contract"
        fi
        while read -r key; do
            [ -n "$key" ] || continue
            signature=$(echo "$previous" | jq -r --arg k "$key" --arg s "$section" '.[$s][$k].signature')
            echo "CRITICAL: $contract: $section entry '$signature' ($key) was removed or its hash changed!"
            breaking=true
        done <<<"$gone"

        if ! added=$(removed_keys "$current" "$previous" "$section"); then
            compare_error "$contract"
        fi
        while read -r key; do
            [ -n "$key" ] || continue
            signature=$(echo "$current" | jq -r --arg k "$key" --arg s "$section" '.[$s][$k].signature')
            echo "NOTE: $contract: new $section entry '$signature' ($key)."
            additive=true
        done <<<"$added"

        # Functions and errors are keyed by a 4-byte selector, so two different
        # canonical signatures can share a key. Nothing above would notice:
        # the entry looks present on both sides while old calldata is decoded
        # under a different input layout.
        if ! shared=$(common_keys "$previous" "$current" "$section"); then
            compare_error "$contract"
        fi
        while read -r key; do
            [ -n "$key" ] || continue
            old_signature=$(echo "$previous" | jq -r --arg k "$key" --arg s "$section" '.[$s][$k].signature')
            new_signature=$(echo "$current" | jq -r --arg k "$key" --arg s "$section" '.[$s][$k].signature')
            if [ "$old_signature" != "$new_signature" ]; then
                echo "CRITICAL: $contract: $section key $key now resolves to '$new_signature' instead of '$old_signature'!"
                breaking=true
            fi
        done <<<"$shared"
    done

    # topic0 does not cover indexedness, so an indexed flip keeps the same key
    # while moving a field between topics and data. Historical decoders break
    # silently on exactly this change, so it is compared separately.
    if ! shared_events=$(common_keys "$previous" "$current" events); then
        compare_error "$contract"
    fi
    while read -r key; do
        [ -n "$key" ] || continue
        signature=$(echo "$previous" | jq -r --arg k "$key" '.events[$k].signature')
        old_indexed=$(echo "$previous" | jq -r --arg k "$key" '.events[$k].indexed')
        new_indexed=$(echo "$current" | jq -r --arg k "$key" '.events[$k].indexed')
        old_anonymous=$(echo "$previous" | jq -r --arg k "$key" '.events[$k].anonymous')
        new_anonymous=$(echo "$current" | jq -r --arg k "$key" '.events[$k].anonymous')

        if [ "$old_indexed" != "$new_indexed" ]; then
            echo "CRITICAL: $contract: event '$signature' indexed layout changed from $old_indexed to $new_indexed!"
            breaking=true
        fi
        if [ "$old_anonymous" != "$new_anonymous" ]; then
            echo "CRITICAL: $contract: event '$signature' anonymous changed from $old_anonymous to $new_anonymous!"
            breaking=true
        fi
    done <<<"$shared_events"

    if ! shared_functions=$(common_keys "$previous" "$current" functions); then
        compare_error "$contract"
    fi
    while read -r key; do
        [ -n "$key" ] || continue
        signature=$(echo "$previous" | jq -r --arg k "$key" '.functions[$k].signature')
        old_mutability=$(echo "$previous" | jq -r --arg k "$key" '.functions[$k].stateMutability')
        new_mutability=$(echo "$current" | jq -r --arg k "$key" '.functions[$k].stateMutability')
        old_outputs=$(echo "$previous" | jq -r --arg k "$key" '.functions[$k].outputs')
        new_outputs=$(echo "$current" | jq -r --arg k "$key" '.functions[$k].outputs')

        # The selector covers only the inputs, so a changed return type or arity
        # keeps the same key while breaking every eth_call decoder.
        if [ "$old_outputs" != "$new_outputs" ]; then
            echo "CRITICAL: $contract: function '$signature' return types changed from ($old_outputs) to ($new_outputs)!"
            breaking=true
        fi

        if [ "$old_mutability" != "$new_mutability" ]; then
            case "$(mutability_change "$old_mutability" "$new_mutability")" in
            tightened)
                echo "CRITICAL: $contract: function '$signature' mutability tightened from $old_mutability to $new_mutability!"
                breaking=true
                ;;
            *)
                echo "NOTE: $contract: function '$signature' mutability relaxed from $old_mutability to $new_mutability."
                additive=true
                ;;
            esac
        fi
    done <<<"$shared_functions"
done

if $breaking; then
    echo ""
    echo "ABI COMPATIBILITY BREAK DETECTED - This will break off-chain callers and log decoders!"
    exit 2
fi

if $additive; then
    echo ""
    echo "ABI has changed, but only additively."
    exit 1
fi

echo "ABI unchanged."
exit 0
