[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.ci]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[profile.snapshot]
no_match_test = "^invariant_"

[profile.v2]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable"]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
