//! Alloy bindings for the Credible Layer protocol contracts.
//!
//! The ABI snapshot is generated by the repository's artifact pipeline. It is
//! committed so registry and git consumers do not need Foundry or submodules.

use alloy_sol_types::sol;

sol!(StateOracle, "abi/StateOracle.json");

#[cfg(test)]
mod tests {
    use alloy_sol_types::{SolCall, SolError, SolEvent, TopicList};

    use super::StateOracle;

    #[test]
    fn state_oracle_boundary_matches_representative_canonical_entries() {
        assert_eq!(
            StateOracle::registerAssertionAdopterCall::SIGNATURE,
            "registerAssertionAdopter(address,address,bytes)"
        );
        assert_eq!(
            StateOracle::getAssertionWindowCall::SIGNATURE,
            "getAssertionWindow(address,bytes32)"
        );
        assert_eq!(
            StateOracle::AssertionAdded::SIGNATURE,
            "AssertionAdded(address,bytes32,uint256,address,bytes,bytes)"
        );
        assert_eq!(
            StateOracle::InvalidDAProof::SIGNATURE,
            "InvalidDAProof(address)"
        );
        assert_eq!(
            <<StateOracle::AssertionAdded as SolEvent>::TopicList as TopicList>::COUNT,
            4
        );
    }
}
